//! Leptos port of [Lucide](https://lucide.dev/).
//!
//! Lucide is a beautiful & consistent icon toolkit made by the community.
//!
//! See [the Rust Lucide book](https://lucide.rustforweb.org/leptos.html) for more documenation.

mod a_arrow_down;
mod a_arrow_up;
mod a_large_small;
mod accessibility;
mod activity;
mod air_vent;
mod airplay;
mod alarm_clock;
mod alarm_clock_check;
mod alarm_clock_minus;
mod alarm_clock_off;
mod alarm_clock_plus;
mod alarm_smoke;
mod album;
mod align_center;
mod align_center_horizontal;
mod align_center_vertical;
mod align_end_horizontal;
mod align_end_vertical;
mod align_horizontal_distribute_center;
mod align_horizontal_distribute_end;
mod align_horizontal_distribute_start;
mod align_horizontal_justify_center;
mod align_horizontal_justify_end;
mod align_horizontal_justify_start;
mod align_horizontal_space_around;
mod align_horizontal_space_between;
mod align_justify;
mod align_left;
mod align_right;
mod align_start_horizontal;
mod align_start_vertical;
mod align_vertical_distribute_center;
mod align_vertical_distribute_end;
mod align_vertical_distribute_start;
mod align_vertical_justify_center;
mod align_vertical_justify_end;
mod align_vertical_justify_start;
mod align_vertical_space_around;
mod align_vertical_space_between;
mod ambulance;
mod ampersand;
mod ampersands;
mod amphora;
mod anchor;
mod angry;
mod annoyed;
mod antenna;
mod anvil;
mod aperture;
mod app_window;
mod app_window_mac;
mod apple;
mod archive;
mod archive_restore;
mod archive_x;
mod armchair;
mod arrow_big_down;
mod arrow_big_down_dash;
mod arrow_big_left;
mod arrow_big_left_dash;
mod arrow_big_right;
mod arrow_big_right_dash;
mod arrow_big_up;
mod arrow_big_up_dash;
mod arrow_down;
mod arrow_down_0_1;
mod arrow_down_1_0;
mod arrow_down_a_z;
mod arrow_down_from_line;
mod arrow_down_left;
mod arrow_down_narrow_wide;
mod arrow_down_right;
mod arrow_down_to_dot;
mod arrow_down_to_line;
mod arrow_down_up;
mod arrow_down_wide_narrow;
mod arrow_down_z_a;
mod arrow_left;
mod arrow_left_from_line;
mod arrow_left_right;
mod arrow_left_to_line;
mod arrow_right;
mod arrow_right_from_line;
mod arrow_right_left;
mod arrow_right_to_line;
mod arrow_up;
mod arrow_up_0_1;
mod arrow_up_1_0;
mod arrow_up_a_z;
mod arrow_up_down;
mod arrow_up_from_dot;
mod arrow_up_from_line;
mod arrow_up_left;
mod arrow_up_narrow_wide;
mod arrow_up_right;
mod arrow_up_to_line;
mod arrow_up_wide_narrow;
mod arrow_up_z_a;
mod arrows_up_from_line;
mod asterisk;
mod at_sign;
mod atom;
mod audio_lines;
mod audio_waveform;
mod award;
mod axe;
mod axis_3_d;
mod baby;
mod backpack;
mod badge;
mod badge_alert;
mod badge_cent;
mod badge_check;
mod badge_dollar_sign;
mod badge_euro;
mod badge_help;
mod badge_indian_rupee;
mod badge_info;
mod badge_japanese_yen;
mod badge_minus;
mod badge_percent;
mod badge_plus;
mod badge_pound_sterling;
mod badge_russian_ruble;
mod badge_swiss_franc;
mod badge_x;
mod baggage_claim;
mod ban;
mod banana;
mod bandage;
mod banknote;
mod barcode;
mod baseline;
mod bath;
mod battery;
mod battery_charging;
mod battery_full;
mod battery_low;
mod battery_medium;
mod battery_warning;
mod beaker;
mod bean;
mod bean_off;
mod bed;
mod bed_double;
mod bed_single;
mod beef;
mod beer;
mod beer_off;
mod bell;
mod bell_dot;
mod bell_electric;
mod bell_minus;
mod bell_off;
mod bell_plus;
mod bell_ring;
mod between_horizontal_end;
mod between_horizontal_start;
mod between_vertical_end;
mod between_vertical_start;
mod biceps_flexed;
mod bike;
mod binary;
mod binoculars;
mod biohazard;
mod bird;
mod bitcoin;
mod blend;
mod blinds;
mod blocks;
mod bluetooth;
mod bluetooth_connected;
mod bluetooth_off;
mod bluetooth_searching;
mod bold;
mod bolt;
mod bomb;
mod bone;
mod book;
mod book_a;
mod book_audio;
mod book_check;
mod book_copy;
mod book_dashed;
mod book_down;
mod book_headphones;
mod book_heart;
mod book_image;
mod book_key;
mod book_lock;
mod book_marked;
mod book_minus;
mod book_open;
mod book_open_check;
mod book_open_text;
mod book_plus;
mod book_text;
mod book_type;
mod book_up;
mod book_up_2;
mod book_user;
mod book_x;
mod bookmark;
mod bookmark_check;
mod bookmark_minus;
mod bookmark_plus;
mod bookmark_x;
mod boom_box;
mod bot;
mod bot_message_square;
mod bot_off;
mod r#box;
mod boxes;
mod braces;
mod brackets;
mod brain;
mod brain_circuit;
mod brain_cog;
mod brick_wall;
mod briefcase;
mod briefcase_business;
mod briefcase_conveyor_belt;
mod briefcase_medical;
mod bring_to_front;
mod brush;
mod bug;
mod bug_off;
mod bug_play;
mod building;
mod building_2;
mod bus;
mod bus_front;
mod cable;
mod cable_car;
mod cake;
mod cake_slice;
mod calculator;
mod calendar;
mod calendar_1;
mod calendar_arrow_down;
mod calendar_arrow_up;
mod calendar_check;
mod calendar_check_2;
mod calendar_clock;
mod calendar_cog;
mod calendar_days;
mod calendar_fold;
mod calendar_heart;
mod calendar_minus;
mod calendar_minus_2;
mod calendar_off;
mod calendar_plus;
mod calendar_plus_2;
mod calendar_range;
mod calendar_search;
mod calendar_sync;
mod calendar_x;
mod calendar_x_2;
mod camera;
mod camera_off;
mod candy;
mod candy_cane;
mod candy_off;
mod cannabis;
mod captions;
mod captions_off;
mod car;
mod car_front;
mod car_taxi_front;
mod caravan;
mod carrot;
mod case_lower;
mod case_sensitive;
mod case_upper;
mod cassette_tape;
mod cast;
mod castle;
mod cat;
mod cctv;
mod chart_area;
mod chart_bar;
mod chart_bar_big;
mod chart_bar_decreasing;
mod chart_bar_increasing;
mod chart_bar_stacked;
mod chart_candlestick;
mod chart_column;
mod chart_column_big;
mod chart_column_decreasing;
mod chart_column_increasing;
mod chart_column_stacked;
mod chart_gantt;
mod chart_line;
mod chart_network;
mod chart_no_axes_column;
mod chart_no_axes_column_decreasing;
mod chart_no_axes_column_increasing;
mod chart_no_axes_combined;
mod chart_no_axes_gantt;
mod chart_pie;
mod chart_scatter;
mod chart_spline;
mod check;
mod check_check;
mod chef_hat;
mod cherry;
mod chevron_down;
mod chevron_first;
mod chevron_last;
mod chevron_left;
mod chevron_right;
mod chevron_up;
mod chevrons_down;
mod chevrons_down_up;
mod chevrons_left;
mod chevrons_left_right;
mod chevrons_left_right_ellipsis;
mod chevrons_right;
mod chevrons_right_left;
mod chevrons_up;
mod chevrons_up_down;
mod chrome;
mod church;
mod cigarette;
mod cigarette_off;
mod circle;
mod circle_alert;
mod circle_arrow_down;
mod circle_arrow_left;
mod circle_arrow_out_down_left;
mod circle_arrow_out_down_right;
mod circle_arrow_out_up_left;
mod circle_arrow_out_up_right;
mod circle_arrow_right;
mod circle_arrow_up;
mod circle_check;
mod circle_check_big;
mod circle_chevron_down;
mod circle_chevron_left;
mod circle_chevron_right;
mod circle_chevron_up;
mod circle_dashed;
mod circle_divide;
mod circle_dollar_sign;
mod circle_dot;
mod circle_dot_dashed;
mod circle_ellipsis;
mod circle_equal;
mod circle_fading_arrow_up;
mod circle_fading_plus;
mod circle_gauge;
mod circle_help;
mod circle_minus;
mod circle_off;
mod circle_parking;
mod circle_parking_off;
mod circle_pause;
mod circle_percent;
mod circle_play;
mod circle_plus;
mod circle_power;
mod circle_slash;
mod circle_slash_2;
mod circle_stop;
mod circle_user;
mod circle_user_round;
mod circle_x;
mod circuit_board;
mod citrus;
mod clapperboard;
mod clipboard;
mod clipboard_check;
mod clipboard_copy;
mod clipboard_list;
mod clipboard_minus;
mod clipboard_paste;
mod clipboard_pen;
mod clipboard_pen_line;
mod clipboard_plus;
mod clipboard_type;
mod clipboard_x;
mod clock;
mod clock_1;
mod clock_10;
mod clock_11;
mod clock_12;
mod clock_2;
mod clock_3;
mod clock_4;
mod clock_5;
mod clock_6;
mod clock_7;
mod clock_8;
mod clock_9;
mod clock_alert;
mod clock_arrow_down;
mod clock_arrow_up;
mod cloud;
mod cloud_alert;
mod cloud_cog;
mod cloud_download;
mod cloud_drizzle;
mod cloud_fog;
mod cloud_hail;
mod cloud_lightning;
mod cloud_moon;
mod cloud_moon_rain;
mod cloud_off;
mod cloud_rain;
mod cloud_rain_wind;
mod cloud_snow;
mod cloud_sun;
mod cloud_sun_rain;
mod cloud_upload;
mod cloudy;
mod clover;
mod club;
mod code;
mod code_xml;
mod codepen;
mod codesandbox;
mod coffee;
mod cog;
mod coins;
mod columns_2;
mod columns_3;
mod columns_4;
mod combine;
mod command;
mod compass;
mod component;
mod computer;
mod concierge_bell;
mod cone;
mod construction;
mod contact;
mod contact_round;
mod container;
mod contrast;
mod cookie;
mod cooking_pot;
mod copy;
mod copy_check;
mod copy_minus;
mod copy_plus;
mod copy_slash;
mod copy_x;
mod copyleft;
mod copyright;
mod corner_down_left;
mod corner_down_right;
mod corner_left_down;
mod corner_left_up;
mod corner_right_down;
mod corner_right_up;
mod corner_up_left;
mod corner_up_right;
mod cpu;
mod creative_commons;
mod credit_card;
mod croissant;
mod crop;
mod cross;
mod crosshair;
mod crown;
mod cuboid;
mod cup_soda;
mod currency;
mod cylinder;
mod dam;
mod database;
mod database_backup;
mod database_zap;
mod delete;
mod dessert;
mod diameter;
mod diamond;
mod diamond_minus;
mod diamond_percent;
mod diamond_plus;
mod dice_1;
mod dice_2;
mod dice_3;
mod dice_4;
mod dice_5;
mod dice_6;
mod dices;
mod diff;
mod disc;
mod disc_2;
mod disc_3;
mod disc_album;
mod divide;
mod dna;
mod dna_off;
mod dock;
mod dog;
mod dollar_sign;
mod donut;
mod door_closed;
mod door_open;
mod dot;
mod download;
mod drafting_compass;
mod drama;
mod dribbble;
mod drill;
mod droplet;
mod droplet_off;
mod droplets;
mod drum;
mod drumstick;
mod dumbbell;
mod ear;
mod ear_off;
mod earth;
mod earth_lock;
mod eclipse;
mod egg;
mod egg_fried;
mod egg_off;
mod ellipsis;
mod ellipsis_vertical;
mod equal;
mod equal_approximately;
mod equal_not;
mod eraser;
mod ethernet_port;
mod euro;
mod expand;
mod external_link;
mod eye;
mod eye_closed;
mod eye_off;
mod facebook;
mod factory;
mod fan;
mod fast_forward;
mod feather;
mod fence;
mod ferris_wheel;
mod figma;
mod file;
mod file_archive;
mod file_audio;
mod file_audio_2;
mod file_axis_3_d;
mod file_badge;
mod file_badge_2;
mod file_box;
mod file_chart_column;
mod file_chart_column_increasing;
mod file_chart_line;
mod file_chart_pie;
mod file_check;
mod file_check_2;
mod file_clock;
mod file_code;
mod file_code_2;
mod file_cog;
mod file_diff;
mod file_digit;
mod file_down;
mod file_heart;
mod file_image;
mod file_input;
mod file_json;
mod file_json_2;
mod file_key;
mod file_key_2;
mod file_lock;
mod file_lock_2;
mod file_minus;
mod file_minus_2;
mod file_music;
mod file_output;
mod file_pen;
mod file_pen_line;
mod file_plus;
mod file_plus_2;
mod file_question;
mod file_scan;
mod file_search;
mod file_search_2;
mod file_sliders;
mod file_spreadsheet;
mod file_stack;
mod file_symlink;
mod file_terminal;
mod file_text;
mod file_type;
mod file_type_2;
mod file_up;
mod file_user;
mod file_video;
mod file_video_2;
mod file_volume;
mod file_volume_2;
mod file_warning;
mod file_x;
mod file_x_2;
mod files;
mod film;
mod filter;
mod filter_x;
mod fingerprint;
mod fire_extinguisher;
mod fish;
mod fish_off;
mod fish_symbol;
mod flag;
mod flag_off;
mod flag_triangle_left;
mod flag_triangle_right;
mod flame;
mod flame_kindling;
mod flashlight;
mod flashlight_off;
mod flask_conical;
mod flask_conical_off;
mod flask_round;
mod flip_horizontal;
mod flip_horizontal_2;
mod flip_vertical;
mod flip_vertical_2;
mod flower;
mod flower_2;
mod focus;
mod fold_horizontal;
mod fold_vertical;
mod folder;
mod folder_archive;
mod folder_check;
mod folder_clock;
mod folder_closed;
mod folder_code;
mod folder_cog;
mod folder_dot;
mod folder_down;
mod folder_git;
mod folder_git_2;
mod folder_heart;
mod folder_input;
mod folder_kanban;
mod folder_key;
mod folder_lock;
mod folder_minus;
mod folder_open;
mod folder_open_dot;
mod folder_output;
mod folder_pen;
mod folder_plus;
mod folder_root;
mod folder_search;
mod folder_search_2;
mod folder_symlink;
mod folder_sync;
mod folder_tree;
mod folder_up;
mod folder_x;
mod folders;
mod footprints;
mod forklift;
mod forward;
mod frame;
mod framer;
mod frown;
mod fuel;
mod fullscreen;
mod gallery_horizontal;
mod gallery_horizontal_end;
mod gallery_thumbnails;
mod gallery_vertical;
mod gallery_vertical_end;
mod gamepad;
mod gamepad_2;
mod gauge;
mod gavel;
mod gem;
mod ghost;
mod gift;
mod git_branch;
mod git_branch_plus;
mod git_commit_horizontal;
mod git_commit_vertical;
mod git_compare;
mod git_compare_arrows;
mod git_fork;
mod git_graph;
mod git_merge;
mod git_pull_request;
mod git_pull_request_arrow;
mod git_pull_request_closed;
mod git_pull_request_create;
mod git_pull_request_create_arrow;
mod git_pull_request_draft;
mod github;
mod gitlab;
mod glass_water;
mod glasses;
mod globe;
mod globe_lock;
mod goal;
mod grab;
mod graduation_cap;
mod grape;
mod grid_2_x_2;
mod grid_2_x_2_check;
mod grid_2_x_2_plus;
mod grid_2_x_2_x;
mod grid_3_x_3;
mod grip;
mod grip_horizontal;
mod grip_vertical;
mod group;
mod guitar;
mod ham;
mod hammer;
mod hand;
mod hand_coins;
mod hand_heart;
mod hand_helping;
mod hand_metal;
mod hand_platter;
mod handshake;
mod hard_drive;
mod hard_drive_download;
mod hard_drive_upload;
mod hard_hat;
mod hash;
mod haze;
mod hdmi_port;
mod heading;
mod heading_1;
mod heading_2;
mod heading_3;
mod heading_4;
mod heading_5;
mod heading_6;
mod headphone_off;
mod headphones;
mod headset;
mod heart;
mod heart_crack;
mod heart_handshake;
mod heart_off;
mod heart_pulse;
mod heater;
mod hexagon;
mod highlighter;
mod history;
mod hop;
mod hop_off;
mod hospital;
mod hotel;
mod hourglass;
mod house;
mod house_plug;
mod house_plus;
mod ice_cream_bowl;
mod ice_cream_cone;
mod id_card;
mod image;
mod image_down;
mod image_minus;
mod image_off;
mod image_play;
mod image_plus;
mod image_up;
mod image_upscale;
mod images;
mod import;
mod inbox;
mod indent_decrease;
mod indent_increase;
mod indian_rupee;
mod infinity;
mod info;
mod inspection_panel;
mod instagram;
mod italic;
mod iteration_ccw;
mod iteration_cw;
mod japanese_yen;
mod joystick;
mod kanban;
mod key;
mod key_round;
mod key_square;
mod keyboard;
mod keyboard_music;
mod keyboard_off;
mod lamp;
mod lamp_ceiling;
mod lamp_desk;
mod lamp_floor;
mod lamp_wall_down;
mod lamp_wall_up;
mod land_plot;
mod landmark;
mod languages;
mod laptop;
mod laptop_minimal;
mod laptop_minimal_check;
mod lasso;
mod lasso_select;
mod laugh;
mod layers;
mod layers_2;
mod layout_dashboard;
mod layout_grid;
mod layout_list;
mod layout_panel_left;
mod layout_panel_top;
mod layout_template;
mod leaf;
mod leafy_green;
mod lectern;
mod letter_text;
mod library;
mod library_big;
mod life_buoy;
mod ligature;
mod lightbulb;
mod lightbulb_off;
mod link;
mod link_2;
mod link_2_off;
mod linkedin;
mod list;
mod list_check;
mod list_checks;
mod list_collapse;
mod list_end;
mod list_filter;
mod list_filter_plus;
mod list_minus;
mod list_music;
mod list_ordered;
mod list_plus;
mod list_restart;
mod list_start;
mod list_todo;
mod list_tree;
mod list_video;
mod list_x;
mod loader;
mod loader_circle;
mod loader_pinwheel;
mod locate;
mod locate_fixed;
mod locate_off;
mod lock;
mod lock_keyhole;
mod lock_keyhole_open;
mod lock_open;
mod log_in;
mod log_out;
mod logs;
mod lollipop;
mod luggage;
mod magnet;
mod mail;
mod mail_check;
mod mail_minus;
mod mail_open;
mod mail_plus;
mod mail_question;
mod mail_search;
mod mail_warning;
mod mail_x;
mod mailbox;
mod mails;
mod map;
mod map_pin;
mod map_pin_check;
mod map_pin_check_inside;
mod map_pin_house;
mod map_pin_minus;
mod map_pin_minus_inside;
mod map_pin_off;
mod map_pin_plus;
mod map_pin_plus_inside;
mod map_pin_x;
mod map_pin_x_inside;
mod map_pinned;
mod martini;
mod maximize;
mod maximize_2;
mod medal;
mod megaphone;
mod megaphone_off;
mod meh;
mod memory_stick;
mod menu;
mod merge;
mod message_circle;
mod message_circle_code;
mod message_circle_dashed;
mod message_circle_heart;
mod message_circle_more;
mod message_circle_off;
mod message_circle_plus;
mod message_circle_question;
mod message_circle_reply;
mod message_circle_warning;
mod message_circle_x;
mod message_square;
mod message_square_code;
mod message_square_dashed;
mod message_square_diff;
mod message_square_dot;
mod message_square_heart;
mod message_square_lock;
mod message_square_more;
mod message_square_off;
mod message_square_plus;
mod message_square_quote;
mod message_square_reply;
mod message_square_share;
mod message_square_text;
mod message_square_warning;
mod message_square_x;
mod messages_square;
mod mic;
mod mic_off;
mod mic_vocal;
mod microchip;
mod microscope;
mod microwave;
mod milestone;
mod milk;
mod milk_off;
mod minimize;
mod minimize_2;
mod minus;
mod monitor;
mod monitor_check;
mod monitor_cog;
mod monitor_dot;
mod monitor_down;
mod monitor_off;
mod monitor_pause;
mod monitor_play;
mod monitor_smartphone;
mod monitor_speaker;
mod monitor_stop;
mod monitor_up;
mod monitor_x;
mod moon;
mod moon_star;
mod mountain;
mod mountain_snow;
mod mouse;
mod mouse_off;
mod mouse_pointer;
mod mouse_pointer_2;
mod mouse_pointer_ban;
mod mouse_pointer_click;
mod r#move;
mod move_3_d;
mod move_diagonal;
mod move_diagonal_2;
mod move_down;
mod move_down_left;
mod move_down_right;
mod move_horizontal;
mod move_left;
mod move_right;
mod move_up;
mod move_up_left;
mod move_up_right;
mod move_vertical;
mod music;
mod music_2;
mod music_3;
mod music_4;
mod navigation;
mod navigation_2;
mod navigation_2_off;
mod navigation_off;
mod network;
mod newspaper;
mod nfc;
mod notebook;
mod notebook_pen;
mod notebook_tabs;
mod notebook_text;
mod notepad_text;
mod notepad_text_dashed;
mod nut;
mod nut_off;
mod octagon;
mod octagon_alert;
mod octagon_minus;
mod octagon_pause;
mod octagon_x;
mod omega;
mod option;
mod orbit;
mod origami;
mod package;
mod package_2;
mod package_check;
mod package_minus;
mod package_open;
mod package_plus;
mod package_search;
mod package_x;
mod paint_bucket;
mod paint_roller;
mod paintbrush;
mod paintbrush_vertical;
mod palette;
mod panel_bottom;
mod panel_bottom_close;
mod panel_bottom_dashed;
mod panel_bottom_open;
mod panel_left;
mod panel_left_close;
mod panel_left_dashed;
mod panel_left_open;
mod panel_right;
mod panel_right_close;
mod panel_right_dashed;
mod panel_right_open;
mod panel_top;
mod panel_top_close;
mod panel_top_dashed;
mod panel_top_open;
mod panels_left_bottom;
mod panels_right_bottom;
mod panels_top_left;
mod paperclip;
mod parentheses;
mod parking_meter;
mod party_popper;
mod pause;
mod paw_print;
mod pc_case;
mod pen;
mod pen_line;
mod pen_off;
mod pen_tool;
mod pencil;
mod pencil_line;
mod pencil_off;
mod pencil_ruler;
mod pentagon;
mod percent;
mod person_standing;
mod philippine_peso;
mod phone;
mod phone_call;
mod phone_forwarded;
mod phone_incoming;
mod phone_missed;
mod phone_off;
mod phone_outgoing;
mod pi;
mod piano;
mod pickaxe;
mod picture_in_picture;
mod picture_in_picture_2;
mod piggy_bank;
mod pilcrow;
mod pilcrow_left;
mod pilcrow_right;
mod pill;
mod pill_bottle;
mod pin;
mod pin_off;
mod pipette;
mod pizza;
mod plane;
mod plane_landing;
mod plane_takeoff;
mod play;
mod plug;
mod plug_2;
mod plug_zap;
mod plus;
mod pocket;
mod pocket_knife;
mod podcast;
mod pointer;
mod pointer_off;
mod popcorn;
mod popsicle;
mod pound_sterling;
mod power;
mod power_off;
mod presentation;
mod printer;
mod printer_check;
mod projector;
mod proportions;
mod puzzle;
mod pyramid;
mod qr_code;
mod quote;
mod rabbit;
mod radar;
mod radiation;
mod radical;
mod radio;
mod radio_receiver;
mod radio_tower;
mod radius;
mod rail_symbol;
mod rainbow;
mod rat;
mod ratio;
mod receipt;
mod receipt_cent;
mod receipt_euro;
mod receipt_indian_rupee;
mod receipt_japanese_yen;
mod receipt_pound_sterling;
mod receipt_russian_ruble;
mod receipt_swiss_franc;
mod receipt_text;
mod rectangle_ellipsis;
mod rectangle_horizontal;
mod rectangle_vertical;
mod recycle;
mod redo;
mod redo_2;
mod redo_dot;
mod refresh_ccw;
mod refresh_ccw_dot;
mod refresh_cw;
mod refresh_cw_off;
mod refrigerator;
mod regex;
mod remove_formatting;
mod repeat;
mod repeat_1;
mod repeat_2;
mod replace;
mod replace_all;
mod reply;
mod reply_all;
mod rewind;
mod ribbon;
mod rocket;
mod rocking_chair;
mod roller_coaster;
mod rotate_3_d;
mod rotate_ccw;
mod rotate_ccw_square;
mod rotate_cw;
mod rotate_cw_square;
mod route;
mod route_off;
mod router;
mod rows_2;
mod rows_3;
mod rows_4;
mod rss;
mod ruler;
mod russian_ruble;
mod sailboat;
mod salad;
mod sandwich;
mod satellite;
mod satellite_dish;
mod save;
mod save_all;
mod save_off;
mod scale;
mod scale_3_d;
mod scaling;
mod scan;
mod scan_barcode;
mod scan_eye;
mod scan_face;
mod scan_heart;
mod scan_line;
mod scan_qr_code;
mod scan_search;
mod scan_text;
mod school;
mod scissors;
mod scissors_line_dashed;
mod screen_share;
mod screen_share_off;
mod scroll;
mod scroll_text;
mod search;
mod search_check;
mod search_code;
mod search_slash;
mod search_x;
mod section;
mod send;
mod send_horizontal;
mod send_to_back;
mod separator_horizontal;
mod separator_vertical;
mod server;
mod server_cog;
mod server_crash;
mod server_off;
mod settings;
mod settings_2;
mod shapes;
mod share;
mod share_2;
mod sheet;
mod shell;
mod shield;
mod shield_alert;
mod shield_ban;
mod shield_check;
mod shield_ellipsis;
mod shield_half;
mod shield_minus;
mod shield_off;
mod shield_plus;
mod shield_question;
mod shield_x;
mod ship;
mod ship_wheel;
mod shirt;
mod shopping_bag;
mod shopping_basket;
mod shopping_cart;
mod shovel;
mod shower_head;
mod shrink;
mod shrub;
mod shuffle;
mod sigma;
mod signal;
mod signal_high;
mod signal_low;
mod signal_medium;
mod signal_zero;
mod signature;
mod signpost;
mod signpost_big;
mod siren;
mod skip_back;
mod skip_forward;
mod skull;
mod slack;
mod slash;
mod slice;
mod sliders_horizontal;
mod sliders_vertical;
mod smartphone;
mod smartphone_charging;
mod smartphone_nfc;
mod smile;
mod smile_plus;
mod snail;
mod snowflake;
mod sofa;
mod soup;
mod space;
mod spade;
mod sparkle;
mod sparkles;
mod speaker;
mod speech;
mod spell_check;
mod spell_check_2;
mod spline;
mod split;
mod spray_can;
mod sprout;
mod square;
mod square_activity;
mod square_arrow_down;
mod square_arrow_down_left;
mod square_arrow_down_right;
mod square_arrow_left;
mod square_arrow_out_down_left;
mod square_arrow_out_down_right;
mod square_arrow_out_up_left;
mod square_arrow_out_up_right;
mod square_arrow_right;
mod square_arrow_up;
mod square_arrow_up_left;
mod square_arrow_up_right;
mod square_asterisk;
mod square_bottom_dashed_scissors;
mod square_chart_gantt;
mod square_check;
mod square_check_big;
mod square_chevron_down;
mod square_chevron_left;
mod square_chevron_right;
mod square_chevron_up;
mod square_code;
mod square_dashed;
mod square_dashed_bottom;
mod square_dashed_bottom_code;
mod square_dashed_kanban;
mod square_dashed_mouse_pointer;
mod square_divide;
mod square_dot;
mod square_equal;
mod square_function;
mod square_kanban;
mod square_library;
mod square_m;
mod square_menu;
mod square_minus;
mod square_mouse_pointer;
mod square_parking;
mod square_parking_off;
mod square_pen;
mod square_percent;
mod square_pi;
mod square_pilcrow;
mod square_play;
mod square_plus;
mod square_power;
mod square_radical;
mod square_scissors;
mod square_sigma;
mod square_slash;
mod square_split_horizontal;
mod square_split_vertical;
mod square_square;
mod square_stack;
mod square_terminal;
mod square_user;
mod square_user_round;
mod square_x;
mod squircle;
mod squirrel;
mod stamp;
mod star;
mod star_half;
mod star_off;
mod step_back;
mod step_forward;
mod stethoscope;
mod sticker;
mod sticky_note;
mod store;
mod stretch_horizontal;
mod stretch_vertical;
mod strikethrough;
mod subscript;
mod sun;
mod sun_dim;
mod sun_medium;
mod sun_moon;
mod sun_snow;
mod sunrise;
mod sunset;
mod superscript;
mod swatch_book;
mod swiss_franc;
mod switch_camera;
mod sword;
mod swords;
mod syringe;
mod table;
mod table_2;
mod table_cells_merge;
mod table_cells_split;
mod table_columns_split;
mod table_of_contents;
mod table_properties;
mod table_rows_split;
mod tablet;
mod tablet_smartphone;
mod tablets;
mod tag;
mod tags;
mod tally_1;
mod tally_2;
mod tally_3;
mod tally_4;
mod tally_5;
mod tangent;
mod target;
mod telescope;
mod tent;
mod tent_tree;
mod terminal;
mod test_tube;
mod test_tube_diagonal;
mod test_tubes;
mod text;
mod text_cursor;
mod text_cursor_input;
mod text_quote;
mod text_search;
mod text_select;
mod theater;
mod thermometer;
mod thermometer_snowflake;
mod thermometer_sun;
mod thumbs_down;
mod thumbs_up;
mod ticket;
mod ticket_check;
mod ticket_minus;
mod ticket_percent;
mod ticket_plus;
mod ticket_slash;
mod ticket_x;
mod tickets;
mod tickets_plane;
mod timer;
mod timer_off;
mod timer_reset;
mod toggle_left;
mod toggle_right;
mod toilet;
mod tornado;
mod torus;
mod touchpad;
mod touchpad_off;
mod tower_control;
mod toy_brick;
mod tractor;
mod traffic_cone;
mod train_front;
mod train_front_tunnel;
mod train_track;
mod tram_front;
mod trash;
mod trash_2;
mod tree_deciduous;
mod tree_palm;
mod tree_pine;
mod trees;
mod trello;
mod trending_down;
mod trending_up;
mod trending_up_down;
mod triangle;
mod triangle_alert;
mod triangle_right;
mod trophy;
mod truck;
mod turtle;
mod tv;
mod tv_minimal;
mod tv_minimal_play;
mod twitch;
mod twitter;
mod r#type;
mod type_outline;
mod umbrella;
mod umbrella_off;
mod underline;
mod undo;
mod undo_2;
mod undo_dot;
mod unfold_horizontal;
mod unfold_vertical;
mod ungroup;
mod university;
mod unlink;
mod unlink_2;
mod unplug;
mod upload;
mod usb;
mod user;
mod user_check;
mod user_cog;
mod user_minus;
mod user_pen;
mod user_plus;
mod user_round;
mod user_round_check;
mod user_round_cog;
mod user_round_minus;
mod user_round_pen;
mod user_round_plus;
mod user_round_search;
mod user_round_x;
mod user_search;
mod user_x;
mod users;
mod users_round;
mod utensils;
mod utensils_crossed;
mod utility_pole;
mod variable;
mod vault;
mod vegan;
mod venetian_mask;
mod vibrate;
mod vibrate_off;
mod video;
mod video_off;
mod videotape;
mod view;
mod voicemail;
mod volleyball;
mod volume;
mod volume_1;
mod volume_2;
mod volume_off;
mod volume_x;
mod vote;
mod wallet;
mod wallet_cards;
mod wallet_minimal;
mod wallpaper;
mod wand;
mod wand_sparkles;
mod warehouse;
mod washing_machine;
mod watch;
mod waves;
mod waves_ladder;
mod waypoints;
mod webcam;
mod webhook;
mod webhook_off;
mod weight;
mod wheat;
mod wheat_off;
mod whole_word;
mod wifi;
mod wifi_high;
mod wifi_low;
mod wifi_off;
mod wifi_zero;
mod wind;
mod wind_arrow_down;
mod wine;
mod wine_off;
mod workflow;
mod worm;
mod wrap_text;
mod wrench;
mod x;
mod youtube;
mod zap;
mod zap_off;
mod zoom_in;
mod zoom_out;

pub use a_arrow_down::*;
pub use a_arrow_up::*;
pub use a_large_small::*;
pub use accessibility::*;
pub use activity::*;
pub use air_vent::*;
pub use airplay::*;
pub use alarm_clock::*;
pub use alarm_clock_check::*;
pub use alarm_clock_minus::*;
pub use alarm_clock_off::*;
pub use alarm_clock_plus::*;
pub use alarm_smoke::*;
pub use album::*;
pub use align_center::*;
pub use align_center_horizontal::*;
pub use align_center_vertical::*;
pub use align_end_horizontal::*;
pub use align_end_vertical::*;
pub use align_horizontal_distribute_center::*;
pub use align_horizontal_distribute_end::*;
pub use align_horizontal_distribute_start::*;
pub use align_horizontal_justify_center::*;
pub use align_horizontal_justify_end::*;
pub use align_horizontal_justify_start::*;
pub use align_horizontal_space_around::*;
pub use align_horizontal_space_between::*;
pub use align_justify::*;
pub use align_left::*;
pub use align_right::*;
pub use align_start_horizontal::*;
pub use align_start_vertical::*;
pub use align_vertical_distribute_center::*;
pub use align_vertical_distribute_end::*;
pub use align_vertical_distribute_start::*;
pub use align_vertical_justify_center::*;
pub use align_vertical_justify_end::*;
pub use align_vertical_justify_start::*;
pub use align_vertical_space_around::*;
pub use align_vertical_space_between::*;
pub use ambulance::*;
pub use ampersand::*;
pub use ampersands::*;
pub use amphora::*;
pub use anchor::*;
pub use angry::*;
pub use annoyed::*;
pub use antenna::*;
pub use anvil::*;
pub use aperture::*;
pub use app_window::*;
pub use app_window_mac::*;
pub use apple::*;
pub use archive::*;
pub use archive_restore::*;
pub use archive_x::*;
pub use armchair::*;
pub use arrow_big_down::*;
pub use arrow_big_down_dash::*;
pub use arrow_big_left::*;
pub use arrow_big_left_dash::*;
pub use arrow_big_right::*;
pub use arrow_big_right_dash::*;
pub use arrow_big_up::*;
pub use arrow_big_up_dash::*;
pub use arrow_down::*;
pub use arrow_down_0_1::*;
pub use arrow_down_1_0::*;
pub use arrow_down_a_z::*;
pub use arrow_down_from_line::*;
pub use arrow_down_left::*;
pub use arrow_down_narrow_wide::*;
pub use arrow_down_right::*;
pub use arrow_down_to_dot::*;
pub use arrow_down_to_line::*;
pub use arrow_down_up::*;
pub use arrow_down_wide_narrow::*;
pub use arrow_down_z_a::*;
pub use arrow_left::*;
pub use arrow_left_from_line::*;
pub use arrow_left_right::*;
pub use arrow_left_to_line::*;
pub use arrow_right::*;
pub use arrow_right_from_line::*;
pub use arrow_right_left::*;
pub use arrow_right_to_line::*;
pub use arrow_up::*;
pub use arrow_up_0_1::*;
pub use arrow_up_1_0::*;
pub use arrow_up_a_z::*;
pub use arrow_up_down::*;
pub use arrow_up_from_dot::*;
pub use arrow_up_from_line::*;
pub use arrow_up_left::*;
pub use arrow_up_narrow_wide::*;
pub use arrow_up_right::*;
pub use arrow_up_to_line::*;
pub use arrow_up_wide_narrow::*;
pub use arrow_up_z_a::*;
pub use arrows_up_from_line::*;
pub use asterisk::*;
pub use at_sign::*;
pub use atom::*;
pub use audio_lines::*;
pub use audio_waveform::*;
pub use award::*;
pub use axe::*;
pub use axis_3_d::*;
pub use baby::*;
pub use backpack::*;
pub use badge::*;
pub use badge_alert::*;
pub use badge_cent::*;
pub use badge_check::*;
pub use badge_dollar_sign::*;
pub use badge_euro::*;
pub use badge_help::*;
pub use badge_indian_rupee::*;
pub use badge_info::*;
pub use badge_japanese_yen::*;
pub use badge_minus::*;
pub use badge_percent::*;
pub use badge_plus::*;
pub use badge_pound_sterling::*;
pub use badge_russian_ruble::*;
pub use badge_swiss_franc::*;
pub use badge_x::*;
pub use baggage_claim::*;
pub use ban::*;
pub use banana::*;
pub use bandage::*;
pub use banknote::*;
pub use barcode::*;
pub use baseline::*;
pub use bath::*;
pub use battery::*;
pub use battery_charging::*;
pub use battery_full::*;
pub use battery_low::*;
pub use battery_medium::*;
pub use battery_warning::*;
pub use beaker::*;
pub use bean::*;
pub use bean_off::*;
pub use bed::*;
pub use bed_double::*;
pub use bed_single::*;
pub use beef::*;
pub use beer::*;
pub use beer_off::*;
pub use bell::*;
pub use bell_dot::*;
pub use bell_electric::*;
pub use bell_minus::*;
pub use bell_off::*;
pub use bell_plus::*;
pub use bell_ring::*;
pub use between_horizontal_end::*;
pub use between_horizontal_start::*;
pub use between_vertical_end::*;
pub use between_vertical_start::*;
pub use biceps_flexed::*;
pub use bike::*;
pub use binary::*;
pub use binoculars::*;
pub use biohazard::*;
pub use bird::*;
pub use bitcoin::*;
pub use blend::*;
pub use blinds::*;
pub use blocks::*;
pub use bluetooth::*;
pub use bluetooth_connected::*;
pub use bluetooth_off::*;
pub use bluetooth_searching::*;
pub use bold::*;
pub use bolt::*;
pub use bomb::*;
pub use bone::*;
pub use book::*;
pub use book_a::*;
pub use book_audio::*;
pub use book_check::*;
pub use book_copy::*;
pub use book_dashed::*;
pub use book_down::*;
pub use book_headphones::*;
pub use book_heart::*;
pub use book_image::*;
pub use book_key::*;
pub use book_lock::*;
pub use book_marked::*;
pub use book_minus::*;
pub use book_open::*;
pub use book_open_check::*;
pub use book_open_text::*;
pub use book_plus::*;
pub use book_text::*;
pub use book_type::*;
pub use book_up::*;
pub use book_up_2::*;
pub use book_user::*;
pub use book_x::*;
pub use bookmark::*;
pub use bookmark_check::*;
pub use bookmark_minus::*;
pub use bookmark_plus::*;
pub use bookmark_x::*;
pub use boom_box::*;
pub use bot::*;
pub use bot_message_square::*;
pub use bot_off::*;
pub use boxes::*;
pub use braces::*;
pub use brackets::*;
pub use brain::*;
pub use brain_circuit::*;
pub use brain_cog::*;
pub use brick_wall::*;
pub use briefcase::*;
pub use briefcase_business::*;
pub use briefcase_conveyor_belt::*;
pub use briefcase_medical::*;
pub use bring_to_front::*;
pub use brush::*;
pub use bug::*;
pub use bug_off::*;
pub use bug_play::*;
pub use building::*;
pub use building_2::*;
pub use bus::*;
pub use bus_front::*;
pub use cable::*;
pub use cable_car::*;
pub use cake::*;
pub use cake_slice::*;
pub use calculator::*;
pub use calendar::*;
pub use calendar_1::*;
pub use calendar_arrow_down::*;
pub use calendar_arrow_up::*;
pub use calendar_check::*;
pub use calendar_check_2::*;
pub use calendar_clock::*;
pub use calendar_cog::*;
pub use calendar_days::*;
pub use calendar_fold::*;
pub use calendar_heart::*;
pub use calendar_minus::*;
pub use calendar_minus_2::*;
pub use calendar_off::*;
pub use calendar_plus::*;
pub use calendar_plus_2::*;
pub use calendar_range::*;
pub use calendar_search::*;
pub use calendar_sync::*;
pub use calendar_x::*;
pub use calendar_x_2::*;
pub use camera::*;
pub use camera_off::*;
pub use candy::*;
pub use candy_cane::*;
pub use candy_off::*;
pub use cannabis::*;
pub use captions::*;
pub use captions_off::*;
pub use car::*;
pub use car_front::*;
pub use car_taxi_front::*;
pub use caravan::*;
pub use carrot::*;
pub use case_lower::*;
pub use case_sensitive::*;
pub use case_upper::*;
pub use cassette_tape::*;
pub use cast::*;
pub use castle::*;
pub use cat::*;
pub use cctv::*;
pub use chart_area::*;
pub use chart_bar::*;
pub use chart_bar_big::*;
pub use chart_bar_decreasing::*;
pub use chart_bar_increasing::*;
pub use chart_bar_stacked::*;
pub use chart_candlestick::*;
pub use chart_column::*;
pub use chart_column_big::*;
pub use chart_column_decreasing::*;
pub use chart_column_increasing::*;
pub use chart_column_stacked::*;
pub use chart_gantt::*;
pub use chart_line::*;
pub use chart_network::*;
pub use chart_no_axes_column::*;
pub use chart_no_axes_column_decreasing::*;
pub use chart_no_axes_column_increasing::*;
pub use chart_no_axes_combined::*;
pub use chart_no_axes_gantt::*;
pub use chart_pie::*;
pub use chart_scatter::*;
pub use chart_spline::*;
pub use check::*;
pub use check_check::*;
pub use chef_hat::*;
pub use cherry::*;
pub use chevron_down::*;
pub use chevron_first::*;
pub use chevron_last::*;
pub use chevron_left::*;
pub use chevron_right::*;
pub use chevron_up::*;
pub use chevrons_down::*;
pub use chevrons_down_up::*;
pub use chevrons_left::*;
pub use chevrons_left_right::*;
pub use chevrons_left_right_ellipsis::*;
pub use chevrons_right::*;
pub use chevrons_right_left::*;
pub use chevrons_up::*;
pub use chevrons_up_down::*;
pub use chrome::*;
pub use church::*;
pub use cigarette::*;
pub use cigarette_off::*;
pub use circle::*;
pub use circle_alert::*;
pub use circle_arrow_down::*;
pub use circle_arrow_left::*;
pub use circle_arrow_out_down_left::*;
pub use circle_arrow_out_down_right::*;
pub use circle_arrow_out_up_left::*;
pub use circle_arrow_out_up_right::*;
pub use circle_arrow_right::*;
pub use circle_arrow_up::*;
pub use circle_check::*;
pub use circle_check_big::*;
pub use circle_chevron_down::*;
pub use circle_chevron_left::*;
pub use circle_chevron_right::*;
pub use circle_chevron_up::*;
pub use circle_dashed::*;
pub use circle_divide::*;
pub use circle_dollar_sign::*;
pub use circle_dot::*;
pub use circle_dot_dashed::*;
pub use circle_ellipsis::*;
pub use circle_equal::*;
pub use circle_fading_arrow_up::*;
pub use circle_fading_plus::*;
pub use circle_gauge::*;
pub use circle_help::*;
pub use circle_minus::*;
pub use circle_off::*;
pub use circle_parking::*;
pub use circle_parking_off::*;
pub use circle_pause::*;
pub use circle_percent::*;
pub use circle_play::*;
pub use circle_plus::*;
pub use circle_power::*;
pub use circle_slash::*;
pub use circle_slash_2::*;
pub use circle_stop::*;
pub use circle_user::*;
pub use circle_user_round::*;
pub use circle_x::*;
pub use circuit_board::*;
pub use citrus::*;
pub use clapperboard::*;
pub use clipboard::*;
pub use clipboard_check::*;
pub use clipboard_copy::*;
pub use clipboard_list::*;
pub use clipboard_minus::*;
pub use clipboard_paste::*;
pub use clipboard_pen::*;
pub use clipboard_pen_line::*;
pub use clipboard_plus::*;
pub use clipboard_type::*;
pub use clipboard_x::*;
pub use clock::*;
pub use clock_1::*;
pub use clock_10::*;
pub use clock_11::*;
pub use clock_12::*;
pub use clock_2::*;
pub use clock_3::*;
pub use clock_4::*;
pub use clock_5::*;
pub use clock_6::*;
pub use clock_7::*;
pub use clock_8::*;
pub use clock_9::*;
pub use clock_alert::*;
pub use clock_arrow_down::*;
pub use clock_arrow_up::*;
pub use cloud::*;
pub use cloud_alert::*;
pub use cloud_cog::*;
pub use cloud_download::*;
pub use cloud_drizzle::*;
pub use cloud_fog::*;
pub use cloud_hail::*;
pub use cloud_lightning::*;
pub use cloud_moon::*;
pub use cloud_moon_rain::*;
pub use cloud_off::*;
pub use cloud_rain::*;
pub use cloud_rain_wind::*;
pub use cloud_snow::*;
pub use cloud_sun::*;
pub use cloud_sun_rain::*;
pub use cloud_upload::*;
pub use cloudy::*;
pub use clover::*;
pub use club::*;
pub use code::*;
pub use code_xml::*;
pub use codepen::*;
pub use codesandbox::*;
pub use coffee::*;
pub use cog::*;
pub use coins::*;
pub use columns_2::*;
pub use columns_3::*;
pub use columns_4::*;
pub use combine::*;
pub use command::*;
pub use compass::*;
pub use component::*;
pub use computer::*;
pub use concierge_bell::*;
pub use cone::*;
pub use construction::*;
pub use contact::*;
pub use contact_round::*;
pub use container::*;
pub use contrast::*;
pub use cookie::*;
pub use cooking_pot::*;
pub use copy::*;
pub use copy_check::*;
pub use copy_minus::*;
pub use copy_plus::*;
pub use copy_slash::*;
pub use copy_x::*;
pub use copyleft::*;
pub use copyright::*;
pub use corner_down_left::*;
pub use corner_down_right::*;
pub use corner_left_down::*;
pub use corner_left_up::*;
pub use corner_right_down::*;
pub use corner_right_up::*;
pub use corner_up_left::*;
pub use corner_up_right::*;
pub use cpu::*;
pub use creative_commons::*;
pub use credit_card::*;
pub use croissant::*;
pub use crop::*;
pub use cross::*;
pub use crosshair::*;
pub use crown::*;
pub use cuboid::*;
pub use cup_soda::*;
pub use currency::*;
pub use cylinder::*;
pub use dam::*;
pub use database::*;
pub use database_backup::*;
pub use database_zap::*;
pub use delete::*;
pub use dessert::*;
pub use diameter::*;
pub use diamond::*;
pub use diamond_minus::*;
pub use diamond_percent::*;
pub use diamond_plus::*;
pub use dice_1::*;
pub use dice_2::*;
pub use dice_3::*;
pub use dice_4::*;
pub use dice_5::*;
pub use dice_6::*;
pub use dices::*;
pub use diff::*;
pub use disc::*;
pub use disc_2::*;
pub use disc_3::*;
pub use disc_album::*;
pub use divide::*;
pub use dna::*;
pub use dna_off::*;
pub use dock::*;
pub use dog::*;
pub use dollar_sign::*;
pub use donut::*;
pub use door_closed::*;
pub use door_open::*;
pub use dot::*;
pub use download::*;
pub use drafting_compass::*;
pub use drama::*;
pub use dribbble::*;
pub use drill::*;
pub use droplet::*;
pub use droplet_off::*;
pub use droplets::*;
pub use drum::*;
pub use drumstick::*;
pub use dumbbell::*;
pub use ear::*;
pub use ear_off::*;
pub use earth::*;
pub use earth_lock::*;
pub use eclipse::*;
pub use egg::*;
pub use egg_fried::*;
pub use egg_off::*;
pub use ellipsis::*;
pub use ellipsis_vertical::*;
pub use equal::*;
pub use equal_approximately::*;
pub use equal_not::*;
pub use eraser::*;
pub use ethernet_port::*;
pub use euro::*;
pub use expand::*;
pub use external_link::*;
pub use eye::*;
pub use eye_closed::*;
pub use eye_off::*;
pub use facebook::*;
pub use factory::*;
pub use fan::*;
pub use fast_forward::*;
pub use feather::*;
pub use fence::*;
pub use ferris_wheel::*;
pub use figma::*;
pub use file::*;
pub use file_archive::*;
pub use file_audio::*;
pub use file_audio_2::*;
pub use file_axis_3_d::*;
pub use file_badge::*;
pub use file_badge_2::*;
pub use file_box::*;
pub use file_chart_column::*;
pub use file_chart_column_increasing::*;
pub use file_chart_line::*;
pub use file_chart_pie::*;
pub use file_check::*;
pub use file_check_2::*;
pub use file_clock::*;
pub use file_code::*;
pub use file_code_2::*;
pub use file_cog::*;
pub use file_diff::*;
pub use file_digit::*;
pub use file_down::*;
pub use file_heart::*;
pub use file_image::*;
pub use file_input::*;
pub use file_json::*;
pub use file_json_2::*;
pub use file_key::*;
pub use file_key_2::*;
pub use file_lock::*;
pub use file_lock_2::*;
pub use file_minus::*;
pub use file_minus_2::*;
pub use file_music::*;
pub use file_output::*;
pub use file_pen::*;
pub use file_pen_line::*;
pub use file_plus::*;
pub use file_plus_2::*;
pub use file_question::*;
pub use file_scan::*;
pub use file_search::*;
pub use file_search_2::*;
pub use file_sliders::*;
pub use file_spreadsheet::*;
pub use file_stack::*;
pub use file_symlink::*;
pub use file_terminal::*;
pub use file_text::*;
pub use file_type::*;
pub use file_type_2::*;
pub use file_up::*;
pub use file_user::*;
pub use file_video::*;
pub use file_video_2::*;
pub use file_volume::*;
pub use file_volume_2::*;
pub use file_warning::*;
pub use file_x::*;
pub use file_x_2::*;
pub use files::*;
pub use film::*;
pub use filter::*;
pub use filter_x::*;
pub use fingerprint::*;
pub use fire_extinguisher::*;
pub use fish::*;
pub use fish_off::*;
pub use fish_symbol::*;
pub use flag::*;
pub use flag_off::*;
pub use flag_triangle_left::*;
pub use flag_triangle_right::*;
pub use flame::*;
pub use flame_kindling::*;
pub use flashlight::*;
pub use flashlight_off::*;
pub use flask_conical::*;
pub use flask_conical_off::*;
pub use flask_round::*;
pub use flip_horizontal::*;
pub use flip_horizontal_2::*;
pub use flip_vertical::*;
pub use flip_vertical_2::*;
pub use flower::*;
pub use flower_2::*;
pub use focus::*;
pub use fold_horizontal::*;
pub use fold_vertical::*;
pub use folder::*;
pub use folder_archive::*;
pub use folder_check::*;
pub use folder_clock::*;
pub use folder_closed::*;
pub use folder_code::*;
pub use folder_cog::*;
pub use folder_dot::*;
pub use folder_down::*;
pub use folder_git::*;
pub use folder_git_2::*;
pub use folder_heart::*;
pub use folder_input::*;
pub use folder_kanban::*;
pub use folder_key::*;
pub use folder_lock::*;
pub use folder_minus::*;
pub use folder_open::*;
pub use folder_open_dot::*;
pub use folder_output::*;
pub use folder_pen::*;
pub use folder_plus::*;
pub use folder_root::*;
pub use folder_search::*;
pub use folder_search_2::*;
pub use folder_symlink::*;
pub use folder_sync::*;
pub use folder_tree::*;
pub use folder_up::*;
pub use folder_x::*;
pub use folders::*;
pub use footprints::*;
pub use forklift::*;
pub use forward::*;
pub use frame::*;
pub use framer::*;
pub use frown::*;
pub use fuel::*;
pub use fullscreen::*;
pub use gallery_horizontal::*;
pub use gallery_horizontal_end::*;
pub use gallery_thumbnails::*;
pub use gallery_vertical::*;
pub use gallery_vertical_end::*;
pub use gamepad::*;
pub use gamepad_2::*;
pub use gauge::*;
pub use gavel::*;
pub use gem::*;
pub use ghost::*;
pub use gift::*;
pub use git_branch::*;
pub use git_branch_plus::*;
pub use git_commit_horizontal::*;
pub use git_commit_vertical::*;
pub use git_compare::*;
pub use git_compare_arrows::*;
pub use git_fork::*;
pub use git_graph::*;
pub use git_merge::*;
pub use git_pull_request::*;
pub use git_pull_request_arrow::*;
pub use git_pull_request_closed::*;
pub use git_pull_request_create::*;
pub use git_pull_request_create_arrow::*;
pub use git_pull_request_draft::*;
pub use github::*;
pub use gitlab::*;
pub use glass_water::*;
pub use glasses::*;
pub use globe::*;
pub use globe_lock::*;
pub use goal::*;
pub use grab::*;
pub use graduation_cap::*;
pub use grape::*;
pub use grid_2_x_2::*;
pub use grid_2_x_2_check::*;
pub use grid_2_x_2_plus::*;
pub use grid_2_x_2_x::*;
pub use grid_3_x_3::*;
pub use grip::*;
pub use grip_horizontal::*;
pub use grip_vertical::*;
pub use group::*;
pub use guitar::*;
pub use ham::*;
pub use hammer::*;
pub use hand::*;
pub use hand_coins::*;
pub use hand_heart::*;
pub use hand_helping::*;
pub use hand_metal::*;
pub use hand_platter::*;
pub use handshake::*;
pub use hard_drive::*;
pub use hard_drive_download::*;
pub use hard_drive_upload::*;
pub use hard_hat::*;
pub use hash::*;
pub use haze::*;
pub use hdmi_port::*;
pub use heading::*;
pub use heading_1::*;
pub use heading_2::*;
pub use heading_3::*;
pub use heading_4::*;
pub use heading_5::*;
pub use heading_6::*;
pub use headphone_off::*;
pub use headphones::*;
pub use headset::*;
pub use heart::*;
pub use heart_crack::*;
pub use heart_handshake::*;
pub use heart_off::*;
pub use heart_pulse::*;
pub use heater::*;
pub use hexagon::*;
pub use highlighter::*;
pub use history::*;
pub use hop::*;
pub use hop_off::*;
pub use hospital::*;
pub use hotel::*;
pub use hourglass::*;
pub use house::*;
pub use house_plug::*;
pub use house_plus::*;
pub use ice_cream_bowl::*;
pub use ice_cream_cone::*;
pub use id_card::*;
pub use image::*;
pub use image_down::*;
pub use image_minus::*;
pub use image_off::*;
pub use image_play::*;
pub use image_plus::*;
pub use image_up::*;
pub use image_upscale::*;
pub use images::*;
pub use import::*;
pub use inbox::*;
pub use indent_decrease::*;
pub use indent_increase::*;
pub use indian_rupee::*;
pub use infinity::*;
pub use info::*;
pub use inspection_panel::*;
pub use instagram::*;
pub use italic::*;
pub use iteration_ccw::*;
pub use iteration_cw::*;
pub use japanese_yen::*;
pub use joystick::*;
pub use kanban::*;
pub use key::*;
pub use key_round::*;
pub use key_square::*;
pub use keyboard::*;
pub use keyboard_music::*;
pub use keyboard_off::*;
pub use lamp::*;
pub use lamp_ceiling::*;
pub use lamp_desk::*;
pub use lamp_floor::*;
pub use lamp_wall_down::*;
pub use lamp_wall_up::*;
pub use land_plot::*;
pub use landmark::*;
pub use languages::*;
pub use laptop::*;
pub use laptop_minimal::*;
pub use laptop_minimal_check::*;
pub use lasso::*;
pub use lasso_select::*;
pub use laugh::*;
pub use layers::*;
pub use layers_2::*;
pub use layout_dashboard::*;
pub use layout_grid::*;
pub use layout_list::*;
pub use layout_panel_left::*;
pub use layout_panel_top::*;
pub use layout_template::*;
pub use leaf::*;
pub use leafy_green::*;
pub use lectern::*;
pub use letter_text::*;
pub use library::*;
pub use library_big::*;
pub use life_buoy::*;
pub use ligature::*;
pub use lightbulb::*;
pub use lightbulb_off::*;
pub use link::*;
pub use link_2::*;
pub use link_2_off::*;
pub use linkedin::*;
pub use list::*;
pub use list_check::*;
pub use list_checks::*;
pub use list_collapse::*;
pub use list_end::*;
pub use list_filter::*;
pub use list_filter_plus::*;
pub use list_minus::*;
pub use list_music::*;
pub use list_ordered::*;
pub use list_plus::*;
pub use list_restart::*;
pub use list_start::*;
pub use list_todo::*;
pub use list_tree::*;
pub use list_video::*;
pub use list_x::*;
pub use loader::*;
pub use loader_circle::*;
pub use loader_pinwheel::*;
pub use locate::*;
pub use locate_fixed::*;
pub use locate_off::*;
pub use lock::*;
pub use lock_keyhole::*;
pub use lock_keyhole_open::*;
pub use lock_open::*;
pub use log_in::*;
pub use log_out::*;
pub use logs::*;
pub use lollipop::*;
pub use luggage::*;
pub use magnet::*;
pub use mail::*;
pub use mail_check::*;
pub use mail_minus::*;
pub use mail_open::*;
pub use mail_plus::*;
pub use mail_question::*;
pub use mail_search::*;
pub use mail_warning::*;
pub use mail_x::*;
pub use mailbox::*;
pub use mails::*;
pub use map::*;
pub use map_pin::*;
pub use map_pin_check::*;
pub use map_pin_check_inside::*;
pub use map_pin_house::*;
pub use map_pin_minus::*;
pub use map_pin_minus_inside::*;
pub use map_pin_off::*;
pub use map_pin_plus::*;
pub use map_pin_plus_inside::*;
pub use map_pin_x::*;
pub use map_pin_x_inside::*;
pub use map_pinned::*;
pub use martini::*;
pub use maximize::*;
pub use maximize_2::*;
pub use medal::*;
pub use megaphone::*;
pub use megaphone_off::*;
pub use meh::*;
pub use memory_stick::*;
pub use menu::*;
pub use merge::*;
pub use message_circle::*;
pub use message_circle_code::*;
pub use message_circle_dashed::*;
pub use message_circle_heart::*;
pub use message_circle_more::*;
pub use message_circle_off::*;
pub use message_circle_plus::*;
pub use message_circle_question::*;
pub use message_circle_reply::*;
pub use message_circle_warning::*;
pub use message_circle_x::*;
pub use message_square::*;
pub use message_square_code::*;
pub use message_square_dashed::*;
pub use message_square_diff::*;
pub use message_square_dot::*;
pub use message_square_heart::*;
pub use message_square_lock::*;
pub use message_square_more::*;
pub use message_square_off::*;
pub use message_square_plus::*;
pub use message_square_quote::*;
pub use message_square_reply::*;
pub use message_square_share::*;
pub use message_square_text::*;
pub use message_square_warning::*;
pub use message_square_x::*;
pub use messages_square::*;
pub use mic::*;
pub use mic_off::*;
pub use mic_vocal::*;
pub use microchip::*;
pub use microscope::*;
pub use microwave::*;
pub use milestone::*;
pub use milk::*;
pub use milk_off::*;
pub use minimize::*;
pub use minimize_2::*;
pub use minus::*;
pub use monitor::*;
pub use monitor_check::*;
pub use monitor_cog::*;
pub use monitor_dot::*;
pub use monitor_down::*;
pub use monitor_off::*;
pub use monitor_pause::*;
pub use monitor_play::*;
pub use monitor_smartphone::*;
pub use monitor_speaker::*;
pub use monitor_stop::*;
pub use monitor_up::*;
pub use monitor_x::*;
pub use moon::*;
pub use moon_star::*;
pub use mountain::*;
pub use mountain_snow::*;
pub use mouse::*;
pub use mouse_off::*;
pub use mouse_pointer::*;
pub use mouse_pointer_2::*;
pub use mouse_pointer_ban::*;
pub use mouse_pointer_click::*;
pub use move_3_d::*;
pub use move_diagonal::*;
pub use move_diagonal_2::*;
pub use move_down::*;
pub use move_down_left::*;
pub use move_down_right::*;
pub use move_horizontal::*;
pub use move_left::*;
pub use move_right::*;
pub use move_up::*;
pub use move_up_left::*;
pub use move_up_right::*;
pub use move_vertical::*;
pub use music::*;
pub use music_2::*;
pub use music_3::*;
pub use music_4::*;
pub use navigation::*;
pub use navigation_2::*;
pub use navigation_2_off::*;
pub use navigation_off::*;
pub use network::*;
pub use newspaper::*;
pub use nfc::*;
pub use notebook::*;
pub use notebook_pen::*;
pub use notebook_tabs::*;
pub use notebook_text::*;
pub use notepad_text::*;
pub use notepad_text_dashed::*;
pub use nut::*;
pub use nut_off::*;
pub use octagon::*;
pub use octagon_alert::*;
pub use octagon_minus::*;
pub use octagon_pause::*;
pub use octagon_x::*;
pub use omega::*;
pub use option::*;
pub use orbit::*;
pub use origami::*;
pub use package::*;
pub use package_2::*;
pub use package_check::*;
pub use package_minus::*;
pub use package_open::*;
pub use package_plus::*;
pub use package_search::*;
pub use package_x::*;
pub use paint_bucket::*;
pub use paint_roller::*;
pub use paintbrush::*;
pub use paintbrush_vertical::*;
pub use palette::*;
pub use panel_bottom::*;
pub use panel_bottom_close::*;
pub use panel_bottom_dashed::*;
pub use panel_bottom_open::*;
pub use panel_left::*;
pub use panel_left_close::*;
pub use panel_left_dashed::*;
pub use panel_left_open::*;
pub use panel_right::*;
pub use panel_right_close::*;
pub use panel_right_dashed::*;
pub use panel_right_open::*;
pub use panel_top::*;
pub use panel_top_close::*;
pub use panel_top_dashed::*;
pub use panel_top_open::*;
pub use panels_left_bottom::*;
pub use panels_right_bottom::*;
pub use panels_top_left::*;
pub use paperclip::*;
pub use parentheses::*;
pub use parking_meter::*;
pub use party_popper::*;
pub use pause::*;
pub use paw_print::*;
pub use pc_case::*;
pub use pen::*;
pub use pen_line::*;
pub use pen_off::*;
pub use pen_tool::*;
pub use pencil::*;
pub use pencil_line::*;
pub use pencil_off::*;
pub use pencil_ruler::*;
pub use pentagon::*;
pub use percent::*;
pub use person_standing::*;
pub use philippine_peso::*;
pub use phone::*;
pub use phone_call::*;
pub use phone_forwarded::*;
pub use phone_incoming::*;
pub use phone_missed::*;
pub use phone_off::*;
pub use phone_outgoing::*;
pub use pi::*;
pub use piano::*;
pub use pickaxe::*;
pub use picture_in_picture::*;
pub use picture_in_picture_2::*;
pub use piggy_bank::*;
pub use pilcrow::*;
pub use pilcrow_left::*;
pub use pilcrow_right::*;
pub use pill::*;
pub use pill_bottle::*;
pub use pin::*;
pub use pin_off::*;
pub use pipette::*;
pub use pizza::*;
pub use plane::*;
pub use plane_landing::*;
pub use plane_takeoff::*;
pub use play::*;
pub use plug::*;
pub use plug_2::*;
pub use plug_zap::*;
pub use plus::*;
pub use pocket::*;
pub use pocket_knife::*;
pub use podcast::*;
pub use pointer::*;
pub use pointer_off::*;
pub use popcorn::*;
pub use popsicle::*;
pub use pound_sterling::*;
pub use power::*;
pub use power_off::*;
pub use presentation::*;
pub use printer::*;
pub use printer_check::*;
pub use projector::*;
pub use proportions::*;
pub use puzzle::*;
pub use pyramid::*;
pub use qr_code::*;
pub use quote::*;
pub use r#box::*;
pub use r#move::*;
pub use r#type::*;
pub use rabbit::*;
pub use radar::*;
pub use radiation::*;
pub use radical::*;
pub use radio::*;
pub use radio_receiver::*;
pub use radio_tower::*;
pub use radius::*;
pub use rail_symbol::*;
pub use rainbow::*;
pub use rat::*;
pub use ratio::*;
pub use receipt::*;
pub use receipt_cent::*;
pub use receipt_euro::*;
pub use receipt_indian_rupee::*;
pub use receipt_japanese_yen::*;
pub use receipt_pound_sterling::*;
pub use receipt_russian_ruble::*;
pub use receipt_swiss_franc::*;
pub use receipt_text::*;
pub use rectangle_ellipsis::*;
pub use rectangle_horizontal::*;
pub use rectangle_vertical::*;
pub use recycle::*;
pub use redo::*;
pub use redo_2::*;
pub use redo_dot::*;
pub use refresh_ccw::*;
pub use refresh_ccw_dot::*;
pub use refresh_cw::*;
pub use refresh_cw_off::*;
pub use refrigerator::*;
pub use regex::*;
pub use remove_formatting::*;
pub use repeat::*;
pub use repeat_1::*;
pub use repeat_2::*;
pub use replace::*;
pub use replace_all::*;
pub use reply::*;
pub use reply_all::*;
pub use rewind::*;
pub use ribbon::*;
pub use rocket::*;
pub use rocking_chair::*;
pub use roller_coaster::*;
pub use rotate_3_d::*;
pub use rotate_ccw::*;
pub use rotate_ccw_square::*;
pub use rotate_cw::*;
pub use rotate_cw_square::*;
pub use route::*;
pub use route_off::*;
pub use router::*;
pub use rows_2::*;
pub use rows_3::*;
pub use rows_4::*;
pub use rss::*;
pub use ruler::*;
pub use russian_ruble::*;
pub use sailboat::*;
pub use salad::*;
pub use sandwich::*;
pub use satellite::*;
pub use satellite_dish::*;
pub use save::*;
pub use save_all::*;
pub use save_off::*;
pub use scale::*;
pub use scale_3_d::*;
pub use scaling::*;
pub use scan::*;
pub use scan_barcode::*;
pub use scan_eye::*;
pub use scan_face::*;
pub use scan_heart::*;
pub use scan_line::*;
pub use scan_qr_code::*;
pub use scan_search::*;
pub use scan_text::*;
pub use school::*;
pub use scissors::*;
pub use scissors_line_dashed::*;
pub use screen_share::*;
pub use screen_share_off::*;
pub use scroll::*;
pub use scroll_text::*;
pub use search::*;
pub use search_check::*;
pub use search_code::*;
pub use search_slash::*;
pub use search_x::*;
pub use section::*;
pub use send::*;
pub use send_horizontal::*;
pub use send_to_back::*;
pub use separator_horizontal::*;
pub use separator_vertical::*;
pub use server::*;
pub use server_cog::*;
pub use server_crash::*;
pub use server_off::*;
pub use settings::*;
pub use settings_2::*;
pub use shapes::*;
pub use share::*;
pub use share_2::*;
pub use sheet::*;
pub use shell::*;
pub use shield::*;
pub use shield_alert::*;
pub use shield_ban::*;
pub use shield_check::*;
pub use shield_ellipsis::*;
pub use shield_half::*;
pub use shield_minus::*;
pub use shield_off::*;
pub use shield_plus::*;
pub use shield_question::*;
pub use shield_x::*;
pub use ship::*;
pub use ship_wheel::*;
pub use shirt::*;
pub use shopping_bag::*;
pub use shopping_basket::*;
pub use shopping_cart::*;
pub use shovel::*;
pub use shower_head::*;
pub use shrink::*;
pub use shrub::*;
pub use shuffle::*;
pub use sigma::*;
pub use signal::*;
pub use signal_high::*;
pub use signal_low::*;
pub use signal_medium::*;
pub use signal_zero::*;
pub use signature::*;
pub use signpost::*;
pub use signpost_big::*;
pub use siren::*;
pub use skip_back::*;
pub use skip_forward::*;
pub use skull::*;
pub use slack::*;
pub use slash::*;
pub use slice::*;
pub use sliders_horizontal::*;
pub use sliders_vertical::*;
pub use smartphone::*;
pub use smartphone_charging::*;
pub use smartphone_nfc::*;
pub use smile::*;
pub use smile_plus::*;
pub use snail::*;
pub use snowflake::*;
pub use sofa::*;
pub use soup::*;
pub use space::*;
pub use spade::*;
pub use sparkle::*;
pub use sparkles::*;
pub use speaker::*;
pub use speech::*;
pub use spell_check::*;
pub use spell_check_2::*;
pub use spline::*;
pub use split::*;
pub use spray_can::*;
pub use sprout::*;
pub use square::*;
pub use square_activity::*;
pub use square_arrow_down::*;
pub use square_arrow_down_left::*;
pub use square_arrow_down_right::*;
pub use square_arrow_left::*;
pub use square_arrow_out_down_left::*;
pub use square_arrow_out_down_right::*;
pub use square_arrow_out_up_left::*;
pub use square_arrow_out_up_right::*;
pub use square_arrow_right::*;
pub use square_arrow_up::*;
pub use square_arrow_up_left::*;
pub use square_arrow_up_right::*;
pub use square_asterisk::*;
pub use square_bottom_dashed_scissors::*;
pub use square_chart_gantt::*;
pub use square_check::*;
pub use square_check_big::*;
pub use square_chevron_down::*;
pub use square_chevron_left::*;
pub use square_chevron_right::*;
pub use square_chevron_up::*;
pub use square_code::*;
pub use square_dashed::*;
pub use square_dashed_bottom::*;
pub use square_dashed_bottom_code::*;
pub use square_dashed_kanban::*;
pub use square_dashed_mouse_pointer::*;
pub use square_divide::*;
pub use square_dot::*;
pub use square_equal::*;
pub use square_function::*;
pub use square_kanban::*;
pub use square_library::*;
pub use square_m::*;
pub use square_menu::*;
pub use square_minus::*;
pub use square_mouse_pointer::*;
pub use square_parking::*;
pub use square_parking_off::*;
pub use square_pen::*;
pub use square_percent::*;
pub use square_pi::*;
pub use square_pilcrow::*;
pub use square_play::*;
pub use square_plus::*;
pub use square_power::*;
pub use square_radical::*;
pub use square_scissors::*;
pub use square_sigma::*;
pub use square_slash::*;
pub use square_split_horizontal::*;
pub use square_split_vertical::*;
pub use square_square::*;
pub use square_stack::*;
pub use square_terminal::*;
pub use square_user::*;
pub use square_user_round::*;
pub use square_x::*;
pub use squircle::*;
pub use squirrel::*;
pub use stamp::*;
pub use star::*;
pub use star_half::*;
pub use star_off::*;
pub use step_back::*;
pub use step_forward::*;
pub use stethoscope::*;
pub use sticker::*;
pub use sticky_note::*;
pub use store::*;
pub use stretch_horizontal::*;
pub use stretch_vertical::*;
pub use strikethrough::*;
pub use subscript::*;
pub use sun::*;
pub use sun_dim::*;
pub use sun_medium::*;
pub use sun_moon::*;
pub use sun_snow::*;
pub use sunrise::*;
pub use sunset::*;
pub use superscript::*;
pub use swatch_book::*;
pub use swiss_franc::*;
pub use switch_camera::*;
pub use sword::*;
pub use swords::*;
pub use syringe::*;
pub use table::*;
pub use table_2::*;
pub use table_cells_merge::*;
pub use table_cells_split::*;
pub use table_columns_split::*;
pub use table_of_contents::*;
pub use table_properties::*;
pub use table_rows_split::*;
pub use tablet::*;
pub use tablet_smartphone::*;
pub use tablets::*;
pub use tag::*;
pub use tags::*;
pub use tally_1::*;
pub use tally_2::*;
pub use tally_3::*;
pub use tally_4::*;
pub use tally_5::*;
pub use tangent::*;
pub use target::*;
pub use telescope::*;
pub use tent::*;
pub use tent_tree::*;
pub use terminal::*;
pub use test_tube::*;
pub use test_tube_diagonal::*;
pub use test_tubes::*;
pub use text::*;
pub use text_cursor::*;
pub use text_cursor_input::*;
pub use text_quote::*;
pub use text_search::*;
pub use text_select::*;
pub use theater::*;
pub use thermometer::*;
pub use thermometer_snowflake::*;
pub use thermometer_sun::*;
pub use thumbs_down::*;
pub use thumbs_up::*;
pub use ticket::*;
pub use ticket_check::*;
pub use ticket_minus::*;
pub use ticket_percent::*;
pub use ticket_plus::*;
pub use ticket_slash::*;
pub use ticket_x::*;
pub use tickets::*;
pub use tickets_plane::*;
pub use timer::*;
pub use timer_off::*;
pub use timer_reset::*;
pub use toggle_left::*;
pub use toggle_right::*;
pub use toilet::*;
pub use tornado::*;
pub use torus::*;
pub use touchpad::*;
pub use touchpad_off::*;
pub use tower_control::*;
pub use toy_brick::*;
pub use tractor::*;
pub use traffic_cone::*;
pub use train_front::*;
pub use train_front_tunnel::*;
pub use train_track::*;
pub use tram_front::*;
pub use trash::*;
pub use trash_2::*;
pub use tree_deciduous::*;
pub use tree_palm::*;
pub use tree_pine::*;
pub use trees::*;
pub use trello::*;
pub use trending_down::*;
pub use trending_up::*;
pub use trending_up_down::*;
pub use triangle::*;
pub use triangle_alert::*;
pub use triangle_right::*;
pub use trophy::*;
pub use truck::*;
pub use turtle::*;
pub use tv::*;
pub use tv_minimal::*;
pub use tv_minimal_play::*;
pub use twitch::*;
pub use twitter::*;
pub use type_outline::*;
pub use umbrella::*;
pub use umbrella_off::*;
pub use underline::*;
pub use undo::*;
pub use undo_2::*;
pub use undo_dot::*;
pub use unfold_horizontal::*;
pub use unfold_vertical::*;
pub use ungroup::*;
pub use university::*;
pub use unlink::*;
pub use unlink_2::*;
pub use unplug::*;
pub use upload::*;
pub use usb::*;
pub use user::*;
pub use user_check::*;
pub use user_cog::*;
pub use user_minus::*;
pub use user_pen::*;
pub use user_plus::*;
pub use user_round::*;
pub use user_round_check::*;
pub use user_round_cog::*;
pub use user_round_minus::*;
pub use user_round_pen::*;
pub use user_round_plus::*;
pub use user_round_search::*;
pub use user_round_x::*;
pub use user_search::*;
pub use user_x::*;
pub use users::*;
pub use users_round::*;
pub use utensils::*;
pub use utensils_crossed::*;
pub use utility_pole::*;
pub use variable::*;
pub use vault::*;
pub use vegan::*;
pub use venetian_mask::*;
pub use vibrate::*;
pub use vibrate_off::*;
pub use video::*;
pub use video_off::*;
pub use videotape::*;
pub use view::*;
pub use voicemail::*;
pub use volleyball::*;
pub use volume::*;
pub use volume_1::*;
pub use volume_2::*;
pub use volume_off::*;
pub use volume_x::*;
pub use vote::*;
pub use wallet::*;
pub use wallet_cards::*;
pub use wallet_minimal::*;
pub use wallpaper::*;
pub use wand::*;
pub use wand_sparkles::*;
pub use warehouse::*;
pub use washing_machine::*;
pub use watch::*;
pub use waves::*;
pub use waves_ladder::*;
pub use waypoints::*;
pub use webcam::*;
pub use webhook::*;
pub use webhook_off::*;
pub use weight::*;
pub use wheat::*;
pub use wheat_off::*;
pub use whole_word::*;
pub use wifi::*;
pub use wifi_high::*;
pub use wifi_low::*;
pub use wifi_off::*;
pub use wifi_zero::*;
pub use wind::*;
pub use wind_arrow_down::*;
pub use wine::*;
pub use wine_off::*;
pub use workflow::*;
pub use worm::*;
pub use wrap_text::*;
pub use wrench::*;
pub use x::*;
pub use youtube::*;
pub use zap::*;
pub use zap_off::*;
pub use zoom_in::*;
pub use zoom_out::*;
